### ISSUE TITLE
Measure gates and qubit relabelling

### ISSUE THREAD

**Issue by yourball** [iic-jku/qcec#1]
Hi,

great project! I was wondering if there is any way to perform equivalence checking in the presence of measure gates using your tool? (after my attempt I got an error message that measure gates are not supported yet).

In fact, most quantum compilation frameworks (e.g. Qiskit, Pytket) quite often perform relabelling of classical registers at the final measurement stage, e.g. 
measure q[0] c[1]
measure q[1] c[0].
 
As a result the circuits are formally not equivalent, but if you would perform measurements and account for relabelling of classical registers so that the measurement results are correct. This trick allows compilers to avoid additional cost of inserting SWAP gates, which would be needed to undo the qubit permutation occurred during the routing.

I would imagine that this should not be very hard to implement in your code?

Thanks!

**Comment by burgholzer** [comment]
Hi,

thanks for your interest in our work!
Currently, measurement gates are not supported due to not being unitary. This is critical whenever intermediate measurements are performed in a circuit. However, in the scenario where measurements just occur at the end of the circuit, this is not a problem.

In fact, the tool already supports input and output qubit relabelling. If a `.qasm` file is provided which contains comments of the form `// i Q_0 Q_1 ... Q_n` and `// o Q_0 Q_1 ... Q_n`.
For example, `// i 2 1 0` means logical qubit q_0 is found at physical qubit Q_2, q_1 at Q_1 and q_2 at Q_0.
Consequently, an instruction `H q[0];` in the circuit file would be translated to a Hadamard on qubit q_2.
Similarly, `// o 1 2 0` indicates that, at the end of the circuit, logical qubit q_0 is found at Q_1, q_1 at Q_2 and q_2 at Q_3.  

I will add the functionality for measurements at the end of the circuits as you suggest in the coming days. Stay Tuned!

**Comment by burgholzer** [comment]
Measurements at the end of circuits are now supported and accordingly change the qubit labelling.
More specifically, a measurement `measure q[0] -> c[1];` specifies that logical qubit q_1 lies on physical/circuit qubit Q_0 at the end of the circuit.

You can additionally specify an initial layout/mapping of logical to physical qubits by providing a line such as `\\ i 2 1 0` in your circuit file.

Let me know if this works for you!

**Comment by yourball** [comment]
Hi,

thanks a lot for implementing this feature! It is very useful.

I tried to do verification on a constrained topology (3 qubits, line connectivity) with Qiskit transpiler optimization level=0 and it worked fine.
However, when I pass optimization level = 1,2,3, qcec_app (with the default 'proportional' verification method as well as with other methods) claims that the circuits are not equivalent.

`Shown in and out non-equivalent with Proportional method (and a maximum of 42 active nodes)`

I'm attaching in.qasm and out.qasm produced by Qiskit transpiler (which are supposed to be equivalent). 
File in.qasm corresponds to transpiled circuit with level=0, out.qasm is transpiled circuit with level=3.

I checked fidelity between two circuits, F=1.

Could please have a look?

[qasms.zip](https://github.com/iic-jku/qcec/files/5331145/qasms.zip)

**Comment by burgholzer** [comment]
Hi,

During the compilation single qubit gates are fused together. So
`u1(1.0) q[0];
u1(0.25*pi) q[0];
u3(0.89,0.72,0.35) q[0];`
becomes
`u3(0.89,0.72,2.1353982) q[0];`.
The problem in this case is that  `2.1353982` is only accurate up to `1e-7` and the tolerance used in our tools is `1e-13` per default. Two quick fixes come to mind:
- Instructing Qiskit to dump higher precision parameters. Replacing `2.1353982` with `2.1353981633974483` solves the problem
- I'm not sure if this is possible, but maybe Qiskit can be instructed to print out symbolic parameters. `u3(0.89,0.72,1.35 + 0.25 * pi) q[0];` also works as expected.

At the moment there is no option to change the default tolerance used in our tool as this is anchored deep down in our software stack. However, I tested with your example, and reducing the tolerance down to `1e-7` indeed allows to show the equivalence.

I hope this helps a little bit. Feel free to send other "problematic" instances our way. I'll push a commit shortly which addresses some potential issues with measurements in circuits and will then have a look at how to allow users to specify a desired tolerance.

**Comment by burgholzer** [comment]
The desired numerical tolerance can now be specified using the `--tol` flag. 
Executing `qcec_app [...]/in.qasm [...]/out.qasm --tol 1e-7` yields the desired result.

**Comment by yourball** [comment]
Great! Now it works perfectly! The issue can be closed.:)

**Comment by burgholzer** [comment]
Wonderful. Feel free to contact us in case of further questions. 👍
