### ISSUE TITLE
EquivalenceChecker.hpp end2 

### ISSUE THREAD

**Issue by devildonkey1392** [iic-jku/qcec#15]
Hi, 

In the include/EquivalenceChecker.hpp, the variable _end2_ is set to _qc1.cend()_.

Is it a mistyping?

I think _end2_ should be set to _qc2.cend()_.

**Comment by burgholzer** [comment]
Hi,

That's just the variable type and no assignment. The iterators are assigned at the very bottom of the corresponding .cpp file.
Although I agree that _decltype(qc2.cend()) end2;_ would have avoided such confusion.

**Comment by devildonkey1392** [comment]
Hi,

I see. 

Thanks for your reply.
