### ISSUE TITLE
Circuit equivalence in the presence of diagonal gates before measure

### ISSUE THREAD

**Issue by yourball** [iic-jku/qcec#4]
Hi,

It seems that two circuits which are different by a diagonal gate just before the measurements will be interpreted as non-equivalent by QCEC checker? Say, two circuits like:

qc1:
X q[0];
measure q[0] -> c[0];

and qc2:
X q[0];
Z q[0];
measure q[0] -> c[0];

The two circuits above implement different unitaries, however the measurement results will be the same.
Is it possible to implement such a functionality (equivalence checker in the presence of diagonal gates before measure gates)?
E.g. Qiskit has a RemoveDiagnoalBeforeMeasure subroutine as a part of transpiler.

**Comment by burgholzer** [comment]
JKQ QCEC now supports an (optional) optimization pass `removeDiagonalGatesBeforeMeasure` which can be used to eliminate diagonal gates before measurements. It can be enabled 
* in Python by passing `removeDiagonalGatesBeforeMeasure=True` to `verify(...)` 
* in the command-line executable by passing the flag `--removeDiagonalGatesBeforeMeasure`.

Note that there may still be some bugs. Let me know if you encounter any!

**Comment by yourball** [comment]
Great, thanks!
