### ISSUE TITLE
Inability to verify qiskit QFT

### ISSUE THREAD

**Issue by jasonlarkin** [iic-jku/qcec#5]
Below is an example with qiskit QFT demonstrating an inability to verify via jkq.qcec with default config.  Also shown is a successful verification via qiskit unitary_simulator and np.allclose.

Am I missing something in the config?

My env:
jkq.qcec             1.8.0

qiskit               0.24.0
qiskit-aer           0.7.6
qiskit-aqua          0.8.2
qiskit-ibmq-provider 0.12.1
qiskit-ignis         0.5.2
qiskit-terra         0.16.4

import networkx as nx
import matplotlib.pyplot as plt

def nngrid(nqbits_x, nqbits_y ):
    G=nx.grid_2d_graph(nqbits_x,nqbits_y)    
    pos = nx.spring_layout(G, iterations=100)
    plt.subplot(221)
    nx.draw(G, pos, font_size=8)
    plt.show()    
    cmap = []
    for edge in G.edges():
        cmap.append([ edge[0][0] + edge[0][1]*nqbits_x  ,\
                     edge[1][0] + edge[1][1]*nqbits_x  ])
    return cmap        

from jkq.qcec import Configuration, Strategy, verify
from qiskit import QuantumCircuit, transpile

basis_gates = ['h', 'cp','swap']
opt_level=0
cmap=nngrid(2,2)
qft = QFT(nqbits)  
qc_tran = transpile(qft,optimization_level=opt_level,\
               basis_gates=basis_gates,\
               coupling_map=cmap)                         

# set dedicated verification strategy
config = Configuration()
#config.strategy = Strategy.compilationflow
#Strategy.naive
#Strategy.proportional
#config.strategy = Strategy.lookahead
#config.tolerance = 1e-8

# verify the compilation result
result = verify(qft, qc_tran, config)
print(result)

simulator = Aer.get_backend("unitary_simulator")

result_qft = execute(qft, simulator).result()
unitary_qft = result_qft.get_unitary(qft)

result_tran = execute(qc_tran, simulator).result()
unitary_tran = result_qft.get_unitary(qc_tran)

np.allclose(unitary_qft, unitary_tran) 

![image](https://user-images.githubusercontent.com/2052476/113078536-4d71d500-91a1-11eb-8a3c-c5706c3e465d.png)

**Comment by burgholzer** [comment]
I just looked at your example. You are indeed missing a small little detail. It might be a bit hidden in the README:
```python
# append measurements to save output mapping of physical to logical (qu)bits
qc.measure_all()
```
Without knowing where qubits are placed at the end of the transpiled circuit, the best you can hope for is showing equivalence up to some permutation of the outputs (which is currently _not_ implemented in our tool). By adding measurements to the end of the original circuit, the output permutation can be restored from the measurements in the transpiled circuit. To the best of my knowledge this is the only way to retrieve where qubits end up in the transpiled circuit as of now. If this has changed somehow in recent versions of Qiskit I would gladly adapt the bindings for our tool.

For now, your problems should be fixed by just adding `qfr.measure_all()`.

I hope this helps. In case of further questions, do not hesitate to contact us!

**Comment by jasonlarkin** [comment]
awesome! this fixed the issue

![image](https://user-images.githubusercontent.com/2052476/113249287-7327d880-928c-11eb-8bc9-07a758890663.png)

**Comment by jasonlarkin** [comment]
awesome! this fixed the issue

![image](https://user-images.githubusercontent.com/2052476/113249287-7327d880-928c-11eb-8bc9-07a758890663.png)

**Comment by jasonlarkin** [comment]
I might have been premature on confirm of fix, here are some updated results

```python
from jkq.qcec import Configuration, Strategy, verify, Equivalence


def qcec_verify(circ1,circ2,Config,dmeas):

    circ1_tmp = circ1.copy()

    circ2_tmp = circ2.copy()    

    if dmeas:

        circ1_tmp.measure_all()

        circ2_tmp.measure_all()    

    result = verify(circ1_tmp, circ2_tmp, Config)

    print(result.equivalence)      

    return

config = Configuration()

config.strategy = Strategy.naive

#config.strategy = Strategy.compilationflow

#Strategy.proportional

#config.strategy = Strategy.lookahead

#config.tolerance = 1e-8

​

basis_gates = ['h', 'cp','swap']

nqbits=4

opt_level=0

cmap=nngrid(2,2)

​

for dswaps in [True,False]:

    for dmeas in [True,False]:

        qft = QFT(nqbits,do_swaps=dswaps)  

        qc_tran = transpile(qft,optimization_level=opt_level,\

                       basis_gates=basis_gates,\

                       coupling_map=cmap)          

        qcec_verify(qft,qc_tran,config,dmeas)

        print('dswaps=',dswaps)

        print('dmeas=',dmeas)        

```

'equivalence' results are obtained, but not consistently (eg over dswaps, dmeas the results change each run):

```bash
Equivalence.not_equivalent
dswaps= True
dmeas= True
Equivalence.not_equivalent
dswaps= True
dmeas= False
Equivalence.equivalent
dswaps= False
dmeas= True
Equivalence.not_equivalent
dswaps= False
dmeas= False
```

```bash
Equivalence.not_equivalent
dswaps= True
dmeas= True
Equivalence.not_equivalent
dswaps= True
dmeas= False
Equivalence.not_equivalent
dswaps= False
dmeas= True
Equivalence.equivalent
dswaps= False
dmeas= False
```

```bash
Equivalence.not_equivalent
dswaps= True
dmeas= True
Equivalence.not_equivalent
dswaps= True
dmeas= False
Equivalence.equivalent
dswaps= False
dmeas= True
Equivalence.equivalent
dswaps= False
dmeas= False
```

and so forth.  Same behavior for you?

**Comment by burgholzer** [comment]
I'll look into this tomorrow!
Might be related to some kind of numerical tolerance.

**Comment by burgholzer** [comment]
Are you still using Qiskit 0.24?
For some unknown reason the transpiler of Qiskit 0.25 can't transpile the QFT circuit to the given basis gate set at O0. (Error message:  `'Flipping of gate direction is only supported for CX and ECR at this time.'`)

I'll downgrade to 0.24 for now and see what I can find.

**Comment by burgholzer** [comment]
I found the issue. In order for the output permutation information to be available (and correct), measurements have to be appended to the circuit _before_ transpiling it. Otherwise the information where logical qubits are mapped to at the end of the circuit is lost. If you modify your loop to
```python
for dswaps in [True, False]:
    for dmeas in [True, False]:
        qft = QFT(nqbits, do_swaps=dswaps)
        if dmeas:
            qft.measure_all()
        qc_tran = transpile(qft,
                            optimization_level=opt_level,
                            basis_gates=basis_gates,
                            coupling_map=cmap)

        result = verify(qft, qc_tran, config)
        print(result.equivalence)
        print('dswaps=', dswaps)
        print('dmeas=', dmeas)
```
I consistently get the expected result:
```shell
Equivalence.equivalent
dswaps= True
dmeas= True
Equivalence.not_equivalent
dswaps= True
dmeas= False
Equivalence.equivalent
dswaps= False
dmeas= True
Equivalence.not_equivalent
dswaps= False
dmeas= False
```
(without measurement information the circuits are only equivalent up to a permutation of the output qubits).

The reason your results changed randomly is because Qiskit's default mapping strategy is stochastic/based on a random seed. Thus, in case a mapping was chosen, where at the end of the circuit logical qubit q_i is still at physical qubit Q_i, the verification succeed's even without the measurement information.

**Comment by jasonlarkin** [comment]
Nice, I'm getting consistent results as well, up to nqbits = 16

```bash
nqbits= 2
Equivalence.equivalent
dswaps= True
dmeas= True
Equivalence.equivalent
dswaps= True
dmeas= False
Equivalence.equivalent
dswaps= False
dmeas= True
Equivalence.equivalent
dswaps= False
dmeas= False
nqbits= 4
Equivalence.equivalent
dswaps= True
dmeas= True
Equivalence.not_equivalent
dswaps= True
dmeas= False
Equivalence.equivalent
dswaps= False
dmeas= True
Equivalence.not_equivalent
dswaps= False
dmeas= False
nqbits= 8
Equivalence.equivalent
dswaps= True
dmeas= True
Equivalence.not_equivalent
dswaps= True
dmeas= False
Equivalence.equivalent
dswaps= False
dmeas= True
Equivalence.not_equivalent
dswaps= False
dmeas= False
nqbits= 16
Equivalence.equivalent
dswaps= True
dmeas= True
Equivalence.not_equivalent
dswaps= True
dmeas= False
Equivalence.equivalent
dswaps= False
dmeas= True
Equivalence.not_equivalent
dswaps= False
dmeas= False
```
